//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSec.Web.DynamicData.FieldTemplates
{


    public partial class GridViewPartialView
    {
        protected global::System.Web.UI.WebControls.Literal Literal1;
    }
}
