CREATE TABLE [dbo].[Users] (
    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
    [FirstName]            NVARCHAR (20)   NOT NULL,
    [LastName]             NVARCHAR (20)   NOT NULL,
    [LoginName]            NVARCHAR (40)   NOT NULL,
    [Password]             NVARCHAR (50)   NOT NULL,
    [Email]                NVARCHAR (50)   NOT NULL,
    [Active]               BIT             NOT NULL,
    [Comment]              NVARCHAR (200)  NULL,
    [ModifiedBy]           NVARCHAR (40)   NOT NULL,
    [ModifiedLast]         DATETIME        NOT NULL,
    [Timestamp]            TIMESTAMP       NOT NULL,
    [OccupationName]       NVARCHAR (100)  NULL,
    [PhoneNumber]          NVARCHAR (100)  NULL,
    [WorkHours]            SMALLINT        NULL,
    [GroupId]              INT             NULL,
    [Birthday]             DATETIME        NULL,
    [Birthplace]           NVARCHAR (100)  NULL,
    [FamilyState]          NVARCHAR (75)   NULL,
    [Citizenship]          NVARCHAR (75)   NULL,
    [Residence]            NVARCHAR (75)   NULL,
    [Nation]               NVARCHAR (75)   NULL,
    [TitleId]              INT             NULL,
    [CompanyId]            INT             NULL,
    [ContractNum]          NVARCHAR (50)   NULL,
    [ContractStartDate]    DATETIME        NULL,
    [ContractEndDate]      DATETIME        NULL,
    [PermitOfWork]         DATETIME        NULL,
    [PermissionCallGuests] BIT             NULL,
    [MillitaryAssignment]  BIT             NULL,
    [Image]                VARBINARY (MAX) NULL,
    [PersonalCode]         NUMERIC (20)    NOT NULL,
    [ExternalPersonalCode] NUMERIC (20)    NOT NULL,
    [LanguageId]           INT             NULL,
    [RegistredStartDate]   DATETIME        NOT NULL,
    [RegistredEndDate]     DATETIME        NOT NULL,
    [TableNumber]          INT             NULL,
    [WorkTime]             BIT             NULL,
    [IsDeleted]            BIT             NOT NULL,
    [CreatedBy]            NVARCHAR (50)   NOT NULL,
    [PIN1]                 INT             NULL,
    [PIN2]                 INT             NULL
);

