ALTER TABLE [dbo].[UserRoles]
    ADD CONSTRAINT [IX_UserRoles] UNIQUE NONCLUSTERED ([RoleId] ASC, [UserId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

